name: Go

on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup PSE
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{secrets.IR_API_KEY_GO}}
          
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Go environment
     # - name: Setup Go
   #     uses: actions/setup-go@v5
       # with:
      #    go-version: 1.21

      # 3. Cache Go modules and build cache
      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-


      # 4. Generate go.sum if missing and download dependencies
    #  - name: Download Go modules and generate go.sum
  #      run: |
     #     if [ ! -f go.sum ]; then
     #       echo "go.sum missing, running go mod tidy..."
      #    fi
      #    go mod tidy

      - name: Install dependencies
        run: go mod download all

    # 5. Optional: Verify downloaded modules
      - name: List cached modules
        run: ls -R ~/go/pkg/mod | head -20

      - name: Cleanup PSE
        if: always()
        uses: invisirisk/pse-action@latest
        with:
          cleanup: "true"

  gather_analytics:
    runs-on: ubuntu-latest
    name: Gather Analytics
    needs: build
    if: always()
    steps:
      - name: Gather Status
        uses: invisirisk/pse-action@latest
        with:
          api_url: "https://app.invisirisk.com"
          app_token: ${{secrets.IR_API_KEY_GO}}
          send_job_status: "true"
          debug: "true"

